/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnail' : IDL.Text,
  'instructor' : IDL.Text,
  'difficulty' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'enrollmentCount' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'studentName' : IDL.Text,
  'quote' : IDL.Text,
  'rating' : IDL.Nat,
  'courseName' : IDL.Text,
  'avatar' : IDL.Text,
});

export const idlService = IDL.Service({
  'enrollInCourse' : IDL.Func([IDL.Text], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
  'getCoursesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
  'getFeaturedCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnail' : IDL.Text,
    'instructor' : IDL.Text,
    'difficulty' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'enrollmentCount' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'studentName' : IDL.Text,
    'quote' : IDL.Text,
    'rating' : IDL.Nat,
    'courseName' : IDL.Text,
    'avatar' : IDL.Text,
  });
  
  return IDL.Service({
    'enrollInCourse' : IDL.Func([IDL.Text], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCourse' : IDL.Func([IDL.Text], [Course], ['query']),
    'getCoursesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Course)], ['query']),
    'getFeaturedCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };