/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'title' : string,
  'duration' : bigint,
  'thumbnail' : string,
  'instructor' : string,
  'difficulty' : string,
  'description' : string,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
  'enrollmentCount' : bigint,
}
export interface Testimonial {
  'studentName' : string,
  'quote' : string,
  'rating' : bigint,
  'courseName' : string,
  'avatar' : string,
}
export interface _SERVICE {
  'enrollInCourse' : ActorMethod<[string], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getCourse' : ActorMethod<[string], Course>,
  'getCoursesByCategory' : ActorMethod<[string], Array<Course>>,
  'getFeaturedCourses' : ActorMethod<[], Array<Course>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];